/**
 * <h1>Drone</h1> Represents a Drone
 *
 * @author Jackson Oriez and Alexmaxfield
 * @version 12/4/2018
 */

public class Drone extends Vehicle {

    final private double gasRate = 1.33;

    /**
     * Default Contructor
     */
    //============================================================================
    public Drone() {

    }

    //============================================================================

    /**
     * Constructor
     *
     * @param licensePlate license plate of vehicle
     * @param maxWeight    maximum weight that the vehicle can hold
     */
    //============================================================================
    public Drone(String licensePlate, double maxWeight) {
        super(licensePlate, maxWeight);
    }

    //============================================================================

    /*
     * =============================================================================
     * | Methods from Profitable Interface
     * =============================================================================
     */

    /**
     * Returns the profits generated by the packages currently in the Truck.
     * <p>
     * &sum;p<sub>price</sub> - (range<sub>max</sub> &times; 1.33)
     * </p>
     */
    @Override
    public double getProfit() {
        double profit = 0;
        double deliveryCost = 0;
        for (int i = 0; i < getPackages().size(); i++) {
            profit += getPackages().get(i).getPrice();
        }
        deliveryCost = getMaxRange() * gasRate;
        profit = profit - deliveryCost;
        return profit;
    }

    /**
     * Generates a String of the Drone report. Drone report includes:
     * <ul>
     * <li>License Plate No.</li>
     * <li>Destination</li>
     * <li>Current Weight/Maximum Weight</li>
     * <li>Net Profit</li>
     * <li>Shipping labels of all packages in truck</li>
     * </ul>
     *
     * @return Truck Report
     */
    @Override
    public String report() {
        String shippingLabels = "";
        for (int i = 0; i < getPackages().size(); i++) {
            shippingLabels += getPackages().get(i).shippingLabel() + "\n";
        }
        return "==========Drone Report==========\nLicense Plate No.: " + getLicensePlate() + "\nDestination: " +
                getZipDest() + "\nWeight Load: " + getCurrentWeight() + "/" + getMaxWeight() + "\nNet Profit: $" +
                getProfit() + "\n=====Shipping Labels=====\n" + shippingLabels + "==============================";
    }


}
