/**
 * <h1>Truck</h1> Represents a Truck
 *
 * @author Jackson Oriez and Alexmaxfield
 * @version 12/4/2018
 */
public class Truck extends Vehicle {

    private final double gasRate = 1.66;

    /**
     * Default Constructor
     */
    //============================================================================
    public Truck() {
    }

    //============================================================================

    /**
     * Constructor
     *
     * @param licensePlate license plate of vehicle
     * @param maxWeight    maximum weight that the vehicle can hold
     */
    //============================================================================
    public Truck(String licensePlate, double maxWeight) {
        super(licensePlate, maxWeight);
    }

    //============================================================================

    /*
     * =============================================================================
     * | Methods from Profitable Interface
     * =============================================================================
     */

    /**
     * Returns the profits generated by the packages currently in the Vehicle.
     * <p>
     * &sum;p<sub>price</sub> - (range<sub>max</sub> &times; 1.66)
     * </p>
     */
    @Override
    public double getProfit() {
        double profit = 0;
        double deliveryCost = 0;
        for (int i = 0; i < getPackages().size(); i++) {
            profit += getPackages().get(i).getPrice();
        }
        deliveryCost = getMaxRange() * gasRate;
        profit = profit - deliveryCost;
        return profit;
    }

    /**
     * Generates a String of the truck report. Truck report includes:
     * <ul>
     * <li>License Plate No.</li>
     * <li>Destination</li>
     * <li>Current Weight/Maximum Weight</li>
     * <li>Net Profit</li>
     * <li>Shipping labels of all packages in truck</li>
     * </ul>
     *
     * @return Truck Report
     */
    @Override
    public String report() {
        String shippingLabels = "";
        for (int i = 0; i < getPackages().size(); i++) {
            shippingLabels += getPackages().get(i).shippingLabel() + "\n";
        }
        return "==========Truck Report==========\nLicense Plate No.: " + getLicensePlate() + "\nDestination: " +
                getZipDest() + "\nWeight Load: " + getCurrentWeight() + "/" + getMaxWeight() + "\nNet Profit: $" +
                getProfit() + "\n=====Shipping Labels=====\n" + shippingLabels + "==============================";
    }
}